variable "instance_type" {}
variable "key_name" {}
variable "ami" {}
variable "vpc_id" {}
variable "user" {}
variable "zone_id" {}
variable "domain" {}
variable "region" {}
variable "ssh_key_location" {}
