variable "region" {}
variable  "ami_centos" {}
variable  "ami_ubuntu" {}
variable  "ami_debian" {}
variable  "min_size_centos" {}
variable  "max_size_centos" {}
variable  "min_size_ubuntu" {}
variable  "max_size_ubuntu" {}
variable  "min_size_debian" {}
variable  "max_size_debian" {}
variable  "subnet" {}
variable  "instance_type_centos" {}
variable  "instance_type_ubuntu" {}
variable  "instance_type_debian" {}
variable  "key_name" {}
variable  "instance_type_windows" {}
variable  "min_size_windows" {}
variable  "max_size_windows" {}
variable  "ami_windows" {}
variable  "vpc_id" {}
