variable "instance_type" {}
variable "key_name" {}
variable "user" {}
variable "ssh_key_location" {}
variable "zone_id" {}
variable "domain" {}
variable "region1" {}
variable "region2" {}
variable "region3" {}
variable "region1_vpc_id" {}
variable "region2_vpc_id" {}
variable "region3_vpc_id" {}
